// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWBUoPQFF_xwwwqqvPVsCZ615pO-ukkY',
    appId: '1:76902935769:web:93c2895e26cfb8b1ba22c8',
    messagingSenderId: '76902935769',
    projectId: 'justfit-d0ad4',
    authDomain: 'justfit-d0ad4.firebaseapp.com',
    storageBucket: 'justfit-d0ad4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHaxWC9Bf16Y2ogYgCNLDW_UznOEJMvI',
    appId: '1:76902935769:android:6e438472c29df0fbba22c8',
    messagingSenderId: '76902935769',
    projectId: 'justfit-d0ad4',
    storageBucket: 'justfit-d0ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACfDp4NQaaCBBHikmgHiDvvDlg9fLuxkU',
    appId: '1:76902935769:ios:c1dec89036e68c19ba22c8',
    messagingSenderId: '76902935769',
    projectId: 'justfit-d0ad4',
    storageBucket: 'justfit-d0ad4.firebasestorage.app',
    iosBundleId: 'com.justfit.justfit',
  );
}
